<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phone [
	<!ELEMENT phone (handphone)+ >
	<!ELEMENT handphone (os, name*, price) >
	<!ELEMENT os (#PCDATA) >
	<!ELEMENT name (#PCDATA) >
	<!ELEMENT price (#PCDATA) >
]>

<!-- 
	기호 : 사용횟수
	+ : 1개 이상
	* : 0개 이상
	? : 0 or 1
	A|B : A또는 B 둘 중 하나만 가능
	() : 요소를 그룹으로 선언해서 사용
 -->
 
<phone>
	<handphone>
		<os>안드로이드</os>
		<name>갤럭시 Z Filp6</name>
		<price>1,485,000</price>
	</handphone>
	
	<handphone>
		<os>iOS</os>
		<name>iPhone 16 Pro</name>
		<price>1,550,000</price>
	</handphone>
</phone>